### ISSUE TITLE
Milestone 1 

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/movie_dashboard#1]
Main stuff:
- [ ] Proposal (Jasmine)
- Motivation and purpose
- Description of the data
 - Research questions you are exploring

- [ ] Description of your app & sketch (Mahsa)

Other: (Sufang)
- [ ] Team work contract
- [ ] collaborative documentation
- [ ] Code of conduct
- [ ] License
- [ ] CONTRIBUTING.md

**Comment by jasmineortega** [comment]
dashboard ideas: movies not tv shows
- Count of location filmed per year (mapped)  ~ slider 
- Number of movies released each month (filter by year)
- Genre of movie in specific year 
- duration vs rating
