### ISSUE TITLE
Milestone 3 

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/movie_dashboard#28]
- [x] Dockerfile/installation instructions
- [x] Favicon/title
- [x] Peer review [link](https://github.com/UBC-MDS/DSCI532-peer-review/issues/30)
- [x] DashR repo: [link](https://github.com/UBC-MDS/movie_dashboard-R)
- [x] Comparing technologies

**Comment by jasmineortega** [comment]
I have followed the instructions for the Favicon but it still doesn't appear to work. Following up with Florencia!

Edit: got it to work by including `__name__` in dash initialization. We're all set!
