### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/movie_dashboard#33]
[Milestone 4](https://pages.github.ubc.ca/mds-2021-22/DSCI_532_viz-2_students/materials/release/milestone4/milestone4.html)
1. Improving app
- [ ] 5 improvement to app:
- [ ] description of changes

2. Finish dashR app
- [ ] combine R dashboards
-  [ ]  update README.md

3. Deployment on Heroku
4. Reflection under `doc/`
