### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by jasmineortega** [UBC-MDS/movie_dashboard#7]
Repo:
- [x] GH folder structure (Jasmine nts: dont forget yaml)
- [ ] Implement the dashboard you outlined in your proposal to be USEABLE (have around 3 plots and most of their widgets and interactivity implemented)
- [x] Group reflection: In this section, your group should document on what you have implemented in your dashboard so far and explain what is not yet implemented. 
- [x] Expand on the README file 
- [x] Deploy your app on Heroku and include the link to your deployed dashboard clearly visible near the top of your README

- [x] create release and submit
